export const newYorkTimesCategories = [
    "Arts",
    "Automobiles",
    "Autos",
    "Blogs",
    "Books",
    "Booming",
    "Business",
    "Business Day",
    "Corrections",
    "Crosswords & Games",
    "Crosswords/Games",
    "Dining & Wine",
    "Dining and Wine",
    "Editors' Notes",
    "Education",
    "Fashion & Style",
    "Food",
    "Front Page",
    "Giving",
    "Global Home",
    "Great Homes & Destinations",
    "Great Homes and Destinations",
    "Health",
    "Home & Garden",
    "Home and Garden",
    "International Home",
    "Job Market",
    "Learning",
    "Magazine",
    "Movies",
    "Multimedia",
    "Multimedia/Photos",
    "N.Y. / Region",
    "N.Y./Region",
    "NYRegion",
    "NYT Now",
    "National",
    "New York",
    "New York and Region",
    "Obituaries",
    "Olympics",
    "Open",
    "Opinion",
    "Paid Death Notices",
    "Public Editor",
    "Real Estate",
    "Science",
    "Sports",
    "Style",
    "Sunday Magazine",
    "Sunday Review",
    "T Magazine",
    "T:Style",
    "Technology",
    "The Public Editor",
    "The Upshot",
    "Theater",
    "Times Topics",
    "TimesMachine",
    "Today's Headlines",
    "Topics",
    "Travel",
    "U.S.",
    "Universal",
    "UrbanEye",
    "Washington",
    "Week in Review",
    "World",
    "Your Money"
  ];

export const newYorkTimesAuthor = [
  "Adam Rasgon",
  "Fatima AbdulKarim",
  "Saif Hasnat",
  "Ben Hubbard",
  "Peter Baker",
  "Jancee Dunn",
  "Julia Jacobs",
  "Michelle Goldberg",
  "David Brooks",
  "Thomas L. Friedman",
  "Paul Krugman",
  "Maureen Dowd",
  "Frank Bruni",
  "David Leonhardt",
  "Nicholas Kristof",
  "Bret Stephens",
  "Gail Collins",
  "Charles M. Blow",
  "Maggie Haberman",
  "Michael D. Shear",
  "Carl Hulse",
  "Sheryl Gay Stolberg",
  "Peter Baker",
  "Glenn Thrush"
];

export const newYorkTimesSources = [
  "The New York Times",
  "Reuters",
  "Associated Press",
  "International Herald Tribune",
  "The Washington Post",
  "The Guardian",
  "BBC News",
  "NPR",
  "Bloomberg",
  "Wall Street Journal",
  "Los Angeles Times",
  "Politico",
  "CNN",
  "ABC News",
  "NBC News",
  "CBS News",
  "Al Jazeera",
  "The Independent",
  "The Telegraph",
  "TIME",
  "USA Today",
  "Newsweek",
  "Forbes",
  "Fox News",
  "BuzzFeed News",
  "HuffPost"
];

export const newYorkTimesBaseUrl = 'https://static01.nyt.com/'
